- name: Aplicar controles
  hosts: web
  become: yes
  tasks:
    - name: Asegurarse de que los servicios innecesarios no estén activos
      ansible.builtin.systemd:
        name: "{{ item }}"
        enable: no
        state: stopped
      loop:
        - autofs
        - avahi-daemon
        - dhcpd
        - named
        - dnsmasq
        - smb
        - vsftpd
        - dovecot
        - nfs-server
        - ypserv
        - cups
        - rpcbind
        - rsyncd
        - snmpd
        - telnet.socket
        - tftp.socket
        - squid
        - httpd
        - nginx
        - xinetd
        - xorg
      ignore_errors: yes
      
    - name: Verificar y eliminar paquetes de servicios no deseados si es necesario
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop:
        - autofs
        - avahi
        - dhcp-server
        - bind
        - dnsmasq
        - samba
        - vsftpd
        - dovecot
        - nfs-utils
        - ypserv
        - cups
        - rpcbind
        - rsync
        - net-snmp
        - telnet-server
        - tftp-server
        - squid
        - httpd
        - nginx
        - xinetd
        - xorg-x11-server-Xorg

    - name: Deshabilitar módulo de cramfs
      ansible.builtin.shell: "modprobe -r cramfs"
      
    - name: Asegurar que cramfs esté deshabilitado permanentemente
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/CIS.conf
        line: "install cramfs /bin/true"
        create: yes

    - name: Habilitar LogLevel INFO
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^LogLevel'
        line: 'LogLevel INFO'

    - name: Configurar política de auditoría para modificaciones de privilegios sudo
      ansible.builtin.lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: '-w /etc/sudoers -p wa -k actions'
        create: yes
        
    - name: Configurar el banner en /etc/issue
      ansible.builtin.copy:
        dest: /etc/issue
        content: |
          ********************************************************************
          * ATENCIÓN: Este sistema es propiedad de Mojito. *
          * El acceso no autorizado o su uso indebido está estrictamente prohibido *
          * y puede ser sancionado legalmente.                                  *
          ********************************************************************

        owner: root
        group: root
        mode: '0644'

    - name: Configurar el banner en /etc/issue.net
      ansible.builtin.copy:
        dest: /etc/issue.net
        content: |
          ********************************************************************
          * ATENCIÓN: Este sistema es propiedad de Mojito. *
          * El acceso no autorizado o su uso indebido está estrictamente prohibido *
          * y puede ser sancionado legalmente.                                  *
          ********************************************************************

        owner: root
        group: root
        mode: '0644'

    - name: Configurar el banner en /etc/motd mensaje del dia
      ansible.builtin.copy:
        dest: /etc/motd
        content: |
          ********************************************************************
          * ATENCIÓN: Este sistema es propiedad de Mojito. *
          * El acceso no autorizado o su uso indebido está estrictamente prohibido *
          * y puede ser sancionado legalmente.                                  *
          ********************************************************************

        owner: root
        group: root
        mode: '0644'

    - name: Asegurar que SSH esté configurado para mostrar el banner
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Banner'
        line: 'Banner /etc/issue.net'
        create: yes
        owner: root
        group: root
        mode: '0600'

    - name: Reinicio servicio SSH  
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Asegurar que las redirecciones ICMP de origen no sean aceptadas (Control 3.3.1)
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.accept_source_route
        value: '0'
        sysctl_set: true
        state: present
        reload: yes

    - name: Asegurar que las redirecciones ICMP no sean aceptadas (Control 3.3.2)
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.accept_redirects
        value: '0'
        sysctl_set: true
        state: present
        reload: yes

    - name: Asegurar que las redirecciones ICMP seguras no sean aceptadas (Control 3.3.3)
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.secure_redirects
        value: '0'
        sysctl_set: true
        state: present
        reload: yes

    - name: Asegurar que los paquetes sospechosos sean registrados (Control 3.3.4)
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.log_martians
        value: '1'
        sysctl_set: true
        state: present
        reload: yes

    - name: Asegurar que las peticiones ICMP broadcast sean ignoradas (Control 3.3.5)
      ansible.posix.sysctl:
        name: net.ipv4.icmp_echo_ignore_broadcasts
        value: '1'
        sysctl_set: true
        state: present
        reload: yes

    - name: Asegurar que las respuestas ICMP falsas sean ignoradas (Control 3.3.6)
      ansible.posix.sysctl:
        name: net.ipv4.icmp_ignore_bogus_error_responses
        value: '1'
        sysctl_set: true
        state: present
        reload: yes

    - name: Asegurar que el filtrado de ruta inversa esté habilitado (Control 3.3.7)
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '1'
        sysctl_set: true
        state: present
        reload: yes

    - name: Asegurar que las cookies TCP SYN estén habilitadas (Control 3.3.8)
      ansible.posix.sysctl:
        name: net.ipv4.tcp_syncookies
        value: '1'
        sysctl_set: true
        state: present
        reload: yes
